GET http://localhost:4000/users
###
GET http://localhost:4000/
###
GET http://localhost:4000/restaurants

###
DELETE http://localhost:4000/restaurants/5ec47477b8bde7bae245eb06

###
GET http://localhost:4000/restaurants-by-permission

###
DELETE http://localhost:4001/logout 
Content-Type: application/json
#Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImRpbWFraXNvQGdtYWlsLmNvbSIsInVzZXJJZCI6IjVlYmQ5NGNkMzBkZGQyMjg4NDIyMGMzYyIsImlhdCI6MTU4OTQ5MjQ1NCwiZXhwIjoxNTg5NDkyNDg0fQ.i0qXnlVwhNTeU67xUvRt5UqHBWqYYiYtsy6TX6MmBMs
#{
#"token": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImRpbWFraXNvQGdtYWlsLmNvbSIsInVzZXJJZCI6IjVlYmQ5NGNkMzBkZGQyMjg4NDIyMGMzYyIsImlhdCI6MTU4OTQ5MjQxOX0.SqO9j8fuTb3TsnsCK6eOT9lOBdkumawFVE6XFDVMoJI"
#}

###
GET http://localhost:4001/token 

###
GET http://localhost:4001/login

###
POST http://localhost:4001/login
Content-Type: application/json

{
    "email": "admin@gmail.com",
    "password": "1234",
    "userId": "5ebd94cd30ddd22884220c3c"
}